---
- hosts: localhost
  vars:
    resource_group_name: "akasurde_rg_2"
    resource_group_location: "eastus"
  tasks:
  - name: Create a resource group named {{ resource_group_name }}
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ resource_group_location }}"
